# Generated by Django 5.0.2 on 2024-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
